version: 2

sources:
  - name: external_source
    meta:
      external_location: 'https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_details-ftp_v1.0_{name}.csv.gz'
    tables:
      - name: d2023_c20231017